### ISSUE TITLE
Github release

### ISSUE THREAD

**Issue by theodelrieu** [grisumbras/enum-flags#10]
Hello!

I wanted to give this library a try today, so I've written a Conan recipe to retrieve the latest commit.

However it would be great to rely on a fixed release number rather than a commit hash, could you make a Github release?

PS:
This might belong in a separate issue, but I've seen the `ENUM_CLASS_FLAGS_FORBID_IMPLICT_CONVERSION` macro in the source code, shouldn't it be exposed? (Making a release with the macro exposed and the typo fixed would be awesome!).

**Comment by grisumbras** [comment]
As you might have guessed, I don't consider the project to be of release quality. For starters, documentation is practically nonexistent. But since there is some interest in it, I feel I should give it some love.

**Comment by grisumbras** [comment]
I created an alpha release (v0.1a). Is it enough for now?

**Comment by theodelrieu** [comment]
That's a good start!

Thanks.
