### ISSUE TITLE
erase implementation

### ISSUE THREAD

**Issue by NikolausDemmel** [grisumbras/enum-flags#23]
The implementation of `erase` looks to me like it only unsets the corresponding flags if they are already set, but if they are unset, it sets them. So its more like a `toggle`:

https://github.com/grisumbras/enum-flags/blob/25f474d6063c658c7bf18a1dc74d781e1cf233dd/include/flags/flags.hpp#L248-L264

I would expect `erase` to always unset. For that, should it be more like `val &= ~e`, or maybe also `val = (val | e) ^ e;`?

**Comment by grisumbras** [comment]
A valid dereferenceable iterator always represents a set flag. If an iterator does not represent a set flag it is either not an iterator into this `flags` instance, or an invalid iterator, or an end iterator. I know, that this is not explicitly documented, as the documentation is still in a very bad state.

`erase` is expected to work with valid iterators into the container, this is in line with standard containers.

**Comment by NikolausDemmel** [comment]
Ah, that makes sense for iterators. What about the second overload? That has nothing to with iterators, right?

Maybe:

```
 size_type erase(enum_type e) noexcept { 
   auto e_count = count(e); 
   val_ |= static_cast<impl_type>(e); 
   val_ ^= static_cast<impl_type>(e); 
   return e_count; 
 }
```

**Comment by grisumbras** [comment]
Oh, you're absolutely correct! This is indeed a bug. Will you provide a PR?

**Comment by NikolausDemmel** [comment]
Sure, will do soon.
