### ISSUE TITLE
Declare enum in class scope and use as flags.

### ISSUE THREAD

**Issue by NikolausDemmel** [grisumbras/enum-flags#26]
I'd like to declare an enumeration at class scope and the use it as flags for a member of the same class. Looks like with enum-flags this is not possible, since the type trait definition needs to be before the first use, but it cannot be at class scope. At the same time, I don't think you can forward declare types at class scope.

Is there any way around this limitation?

```
struct Foo {
    enum Bar { A, B };
    
    // cannot do this at class scope:
    //ALLOW_FLAGS_FOR_ENUM(Bar);
    
    // cannot use before ALLOW_FLAGS_FOR_ENUM
    //flags::flags<Bar> f;
};
```

See also: https://wandbox.org/permlink/FkzOfaxmmaemzy0b

**Comment by grisumbras** [comment]
Currently, the only thing I can suggest is putting the enum into a namespace and then aliasing it in class:

```
namespace detail {
enum Bar { A, B };
ALLOW_FLAGS_FOR_ENUM(Bar);
}

class Foo {
  using Bar = detail::Bar;
  flags::flags<Bar> f;
};
```

**Comment by NikolausDemmel** [comment]
Ah yes, that would work, thanks. But its slightly awekward with naming, since to make things unique you need to use prefixes like, e.g.:

```
namespace detail {
enum class SomeLongClassNameFooBar { A, B };
}

ALLOW_FLAGS_FOR_ENUM(detail::SomeLongClassNameFooBar);

class SomeLongClassNameFoo {
  using Bar = detail::SomeLongClassNameFooBar;
  using BarFlags = flags::flags<Bar>;
  BarFlags f { Bar::A };
};
```

But the good thing is that the usage inside `SomeLongClassNameFoo` is now like I want it to be with short constants `Bar::A` and from outside  `SomeLongClassNameFoo::Bar::A` is also nicely scoped.

PS: I guess `ALLOW_FLAGS_FOR_ENUM` needs to be outside of namespace `detail`...
